# Generated by Django 4.1.3 on 2022-11-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Create')),
                ('update', models.DateField(auto_now_add=True, verbose_name='Create')),
                ('choice', models.CharField(choices=[('Active', 'Активная'), ('Blocked', 'Заблокирован')], default='Active', max_length=15, verbose_name='Choice')),
            ],
        ),
    ]
