# Generated by Django 4.1.3 on 2022-11-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_bookguest_content_alter_bookguest_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookguest',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='Update'),
        ),
    ]
